### PR TITLE
[OpenCL] Use opaque struct for sampler.

### PR DESCRIPTION
**Pull request by yxsamliu**

### CODE REVIEW

**Comment by yxsamliu** [comment]
This one is rebased on tip of amd-common.

**Comment by tstellarAMD** [comment]
Is there a phabricator review that this commit is based off of?

**Comment by yxsamliu** [comment]
Yes https://reviews.llvm.org/D21567

**Comment by tstellarAMD** [comment]
Ok, it looks like we are still making progress getting this upstream.  I'm a little concerned that a commit like this that touches so many files will create a lot of merge conflicts, but this will give as a chance to improve our merge process and make it a little more efficient.

I'm fine with merging this into amd-common.

**Comment by yxsamliu** [comment]
Thanks. Hopefully it will be committed to trunk soon. If it is committed to trunk with changes, shall I revert this pull request?

**Comment by tstellarAMD** [comment]
No, that's OK.  We'll just let the normal merge process run its course.

**Pull request merged**
