### PR TITLE
Merge commits for image support

### PR DESCRIPTION
**Pull request by yxsamliu**

### CODE REVIEW

**Comment by tstellarAMD** [comment]
I've updated amd-common with your merge fixes and metadata fixes, so I think you need to rebase this branch.  Also, I think you can drop "OpenCL] AMDGCN target will generate images in constant address space", because that was committed upstream and is already in amd-common.

**Comment by yxsamliu** [comment]
"[OpenCL] Use opaque struct for sampler." has a dependence on "[OpenCL] AMDGCN target will generate images in constant address space". If I do not include the latter in the same pull request, it may cause conflicts when merging with trunk.

**Comment by tstellarAMD** [comment]
What I'm saying is that since I updated the amd-common branch, this patch is already in amd-common: https://github.com/RadeonOpenCompute/clang/commit/0c8bf1e2bfb7b435f3a223661f52eacb5a77c325

So, this merge request should be rebased on top of amd-common and should only include one commit.

**Comment by yxsamliu** [comment]
I see. will drop it

**Comment by yxsamliu** [comment]
I will close this one and open another.

**Pull request closed without merging**
